run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/anies1212/go-vuln-gate

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
